# Generated by Django 6.1 on 2026-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('stream', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
